# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Davin Landry
# Description of the Site
description: Engineer, Designer, Roboticist, Innovaor
# URL of Image of the Site
site-image: /Davinci_Portfolio/assets/images/ihmc_crop2.jpg
# Keywords of the Site
site-keywords: Site, portfolio, robotics, Engineer, NU 
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /Davinci_Portfolio/assets/images/ihmc_crop2.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: davinlandry2022@u.northwestern.edu
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: davinlandry
github_username:  dlandry97
youtube_channel_id: UCMejJ6cL2sh32slygJIqk_A
rejddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Davin Landry
# URL for the Image of the Author
author-image: /Davinci_Portfolio/assets/images/ihmc_pro_photo_squared.jpg
# 60 Words About the Author
author-about: I am currently pursuing a Master of Science in Robotics at Northwestern University. I graduated from Purdue University in May 2019, where I earned my B.S. in Mechanical engineering and The Certificate of Entrepreneurship and Innovation. After graduating, I gained hands on experience in robotic research and design at The Institute for Human & Machine Cognition (IHMC) in Pensacola, Florida, where I prototyped and assembled the legs and feet of the IHMC's very own hydraulic powered humanoid robot. My passion for robotics and desire to expand my skillset to more than just mechanics brought me to the Northwestern University MSR program.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/dlandry97

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

theme: jekyll-theme-cayman